-- Tabla para historial de partidas
CREATE TABLE IF NOT EXISTS game_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  team_1_name TEXT NOT NULL,
  team_2_name TEXT NOT NULL,
  team_1_score INTEGER NOT NULL,
  team_2_score INTEGER NOT NULL,
  winner TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Habilitar seguridad (RLS)
ALTER TABLE game_history ENABLE ROW LEVEL SECURITY;

-- Políticas
-- 1. Los usuarios pueden ver sus propias partidas
CREATE POLICY "Users can view own game history" 
ON game_history FOR SELECT 
USING (auth.uid() = user_id);

-- 2. Los usuarios pueden insertar sus resultados
CREATE POLICY "Users can insert own game history" 
ON game_history FOR INSERT 
WITH CHECK (auth.uid() = user_id);
